import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/navigation/Header.jsx";
import Footer from "@/components/navigation/Footer.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Diploma Odisha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
